// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module AsciiRayTracer(	// src/main/scala/RayTrace.scala:131:7
  input         clock,	// src/main/scala/RayTrace.scala:131:7
                reset,	// src/main/scala/RayTrace.scala:131:7
  input  [15:0] io_cameraPos_x_value,	// src/main/scala/RayTrace.scala:144:14
                io_cameraPos_y_value,	// src/main/scala/RayTrace.scala:144:14
                io_cameraPos_z_value,	// src/main/scala/RayTrace.scala:144:14
                io_cameraDir_x_value,	// src/main/scala/RayTrace.scala:144:14
                io_cameraDir_y_value,	// src/main/scala/RayTrace.scala:144:14
                io_cameraDir_z_value,	// src/main/scala/RayTrace.scala:144:14
                io_fov,	// src/main/scala/RayTrace.scala:144:14
  output [2:0]  io_sphereAddr,	// src/main/scala/RayTrace.scala:144:14
  input  [15:0] io_sphereData_center_x_value,	// src/main/scala/RayTrace.scala:144:14
                io_sphereData_center_y_value,	// src/main/scala/RayTrace.scala:144:14
                io_sphereData_center_z_value,	// src/main/scala/RayTrace.scala:144:14
                io_sphereData_radius_value,	// src/main/scala/RayTrace.scala:144:14
                io_sphereData_radiusSq_value,	// src/main/scala/RayTrace.scala:144:14
                io_sphereData_specular_value,	// src/main/scala/RayTrace.scala:144:14
                io_sphereData_reflective_value,	// src/main/scala/RayTrace.scala:144:14
  output [1:0]  io_lightAddr,	// src/main/scala/RayTrace.scala:144:14
  input  [15:0] io_lightData_position_x_value,	// src/main/scala/RayTrace.scala:144:14
                io_lightData_position_y_value,	// src/main/scala/RayTrace.scala:144:14
                io_lightData_position_z_value,	// src/main/scala/RayTrace.scala:144:14
                io_lightData_intensity_value,	// src/main/scala/RayTrace.scala:144:14
  input         io_start,	// src/main/scala/RayTrace.scala:144:14
  output        io_busy,	// src/main/scala/RayTrace.scala:144:14
                io_frameComplete,	// src/main/scala/RayTrace.scala:144:14
  output [7:0]  io_asciiChar,	// src/main/scala/RayTrace.scala:144:14
  output        io_asciiValid,	// src/main/scala/RayTrace.scala:144:14
  output [6:0]  io_x,	// src/main/scala/RayTrace.scala:144:14
  output [5:0]  io_y	// src/main/scala/RayTrace.scala:144:14
);

  wire [15:0][6:0] _GEN =
    '{7'h20,
      7'h20,
      7'h20,
      7'h20,
      7'h20,
      7'h20,
      7'h40,
      7'h23,
      7'h25,
      7'h78,
      7'h6F,
      7'h3B,
      7'h3A,
      7'h2C,
      7'h2E,
      7'h20};	// src/main/scala/RayTrace.scala:435:20
  reg  [2:0]       state;	// src/main/scala/RayTrace.scala:178:22
  reg  [6:0]       pixelX;	// src/main/scala/RayTrace.scala:180:23
  reg  [5:0]       pixelY;	// src/main/scala/RayTrace.scala:181:23
  reg  [15:0]      currentRay_origin_x_value;	// src/main/scala/RayTrace.scala:183:27
  reg  [15:0]      currentRay_origin_y_value;	// src/main/scala/RayTrace.scala:183:27
  reg  [15:0]      currentRay_origin_z_value;	// src/main/scala/RayTrace.scala:183:27
  reg  [15:0]      currentRay_dir_x_value;	// src/main/scala/RayTrace.scala:183:27
  reg  [15:0]      currentRay_dir_y_value;	// src/main/scala/RayTrace.scala:183:27
  reg  [15:0]      currentRay_dir_z_value;	// src/main/scala/RayTrace.scala:183:27
  reg  [15:0]      shadowRay_origin_x_value;	// src/main/scala/RayTrace.scala:184:26
  reg  [15:0]      shadowRay_origin_y_value;	// src/main/scala/RayTrace.scala:184:26
  reg  [15:0]      shadowRay_origin_z_value;	// src/main/scala/RayTrace.scala:184:26
  reg  [15:0]      shadowRay_dir_x_value;	// src/main/scala/RayTrace.scala:184:26
  reg  [15:0]      shadowRay_dir_y_value;	// src/main/scala/RayTrace.scala:184:26
  reg  [15:0]      shadowRay_dir_z_value;	// src/main/scala/RayTrace.scala:184:26
  reg  [15:0]      currentIntensity_value;	// src/main/scala/RayTrace.scala:186:33
  reg  [15:0]      cameraForward_x_value;	// src/main/scala/RayTrace.scala:189:30
  reg  [15:0]      cameraForward_y_value;	// src/main/scala/RayTrace.scala:189:30
  reg  [15:0]      cameraForward_z_value;	// src/main/scala/RayTrace.scala:189:30
  reg  [15:0]      cameraRight_x_value;	// src/main/scala/RayTrace.scala:190:28
  reg  [15:0]      cameraRight_y_value;	// src/main/scala/RayTrace.scala:190:28
  reg  [15:0]      cameraRight_z_value;	// src/main/scala/RayTrace.scala:190:28
  reg  [15:0]      cameraUp_x_value;	// src/main/scala/RayTrace.scala:191:25
  reg  [15:0]      cameraUp_y_value;	// src/main/scala/RayTrace.scala:191:25
  reg  [15:0]      cameraUp_z_value;	// src/main/scala/RayTrace.scala:191:25
  reg  [15:0]      screenWidth_value;	// src/main/scala/RayTrace.scala:192:28
  reg  [15:0]      screenHeight_value;	// src/main/scala/RayTrace.scala:193:29
  reg  [2:0]       sphereIdx;	// src/main/scala/RayTrace.scala:195:26
  reg  [2:0]       shadowSphereIdx;	// src/main/scala/RayTrace.scala:196:32
  reg  [1:0]       lightIdx;	// src/main/scala/RayTrace.scala:197:25
  reg  [15:0]      closestT_value;	// src/main/scala/RayTrace.scala:199:25
  reg  [7:0]       closestObj;	// src/main/scala/RayTrace.scala:200:27
  reg              allTested;	// src/main/scala/RayTrace.scala:203:26
  reg  [15:0]      hitPoint_x_value;	// src/main/scala/RayTrace.scala:206:25
  reg  [15:0]      hitPoint_y_value;	// src/main/scala/RayTrace.scala:206:25
  reg  [15:0]      hitPoint_z_value;	// src/main/scala/RayTrace.scala:206:25
  wire             _GEN_0 = state == 3'h0;	// src/main/scala/RayTrace.scala:178:22, :195:26, :278:17
  wire             _GEN_1 = state == 3'h1;	// src/main/scala/RayTrace.scala:178:22, :278:17, :281:15
  wire             _GEN_2 = state == 3'h2;	// src/main/scala/RayTrace.scala:178:22, :278:17, :308:13
  wire             _GEN_3 = state == 3'h3;	// src/main/scala/RayTrace.scala:178:22, :278:17, :336:13
  wire             _GEN_4 = state == 3'h4;	// src/main/scala/RayTrace.scala:178:22, :278:17, :364:17
  wire             _GEN_5 = state == 3'h5;	// src/main/scala/RayTrace.scala:178:22, :272:30, :278:17
  wire             _GEN_6 = state == 3'h6;	// src/main/scala/RayTrace.scala:178:22, :278:17, :396:15
  wire [19:0]      _charIndex_T_2 =
    {4'h0, $signed(currentIntensity_value) < 16'sh100 ? currentIntensity_value : 16'h100}
    * 20'h9;	// src/main/scala/Fixed.scala:70:47, :80:16, src/main/scala/RayTrace.scala:186:33, :259:48, :433:37
  wire             _GEN_7 = _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6;	// src/main/scala/RayTrace.scala:274:16, :278:17
  wire             _GEN_8 = _GEN_0 | _GEN_1 | _GEN_7;	// src/main/scala/RayTrace.scala:274:16, :278:17
  wire             _GEN_9 = _GEN_8 | ~(&state);	// src/main/scala/RayTrace.scala:178:22, :274:16, :278:17
  wire             _GEN_10 = pixelX == 7'h4F;	// src/main/scala/RayTrace.scala:180:23, :440:19
  wire             _GEN_11 = _GEN_10 & pixelY == 6'h27;	// src/main/scala/RayTrace.scala:181:23, :440:{19,37,47}
  always @(posedge clock) begin	// src/main/scala/RayTrace.scala:131:7
    if (reset) begin	// src/main/scala/RayTrace.scala:131:7
      state <= 3'h0;	// src/main/scala/RayTrace.scala:178:22, :195:26
      pixelX <= 7'h0;	// src/main/scala/RayTrace.scala:180:23
      pixelY <= 6'h0;	// src/main/scala/RayTrace.scala:181:23
      currentRay_origin_x_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:{27,40}
      currentRay_origin_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:{27,40}
      currentRay_origin_z_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:{27,40}
      currentRay_dir_x_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:{27,40}
      currentRay_dir_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:{27,40}
      currentRay_dir_z_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:{27,40}
      shadowRay_origin_x_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :184:26
      shadowRay_origin_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :184:26
      shadowRay_origin_z_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :184:26
      shadowRay_dir_x_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :184:26
      shadowRay_dir_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :184:26
      shadowRay_dir_z_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :184:26
      currentIntensity_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :186:33
      cameraForward_x_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :189:30
      cameraForward_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :189:30
      cameraForward_z_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :189:30
      cameraRight_x_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :190:28
      cameraRight_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :190:28
      cameraRight_z_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :190:28
      cameraUp_x_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :191:25
      cameraUp_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :191:25
      cameraUp_z_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :191:25
      screenWidth_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :192:28
      screenHeight_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :193:29
      sphereIdx <= 3'h0;	// src/main/scala/RayTrace.scala:195:26
      shadowSphereIdx <= 3'h0;	// src/main/scala/RayTrace.scala:195:26, :196:32
      lightIdx <= 2'h0;	// src/main/scala/RayTrace.scala:197:25
      closestT_value <= 16'h7FFF;	// <stdin>:94:35, src/main/scala/RayTrace.scala:199:25
      closestObj <= 8'h0;	// src/main/scala/RayTrace.scala:200:27
      allTested <= 1'h0;	// src/main/scala/RayTrace.scala:203:26, :227:50
      hitPoint_x_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :206:25
      hitPoint_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :206:25
      hitPoint_z_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :206:25
    end
    else begin	// src/main/scala/RayTrace.scala:131:7
      automatic logic            _GEN_12 = _GEN_0 | _GEN_1;	// src/main/scala/RayTrace.scala:183:27, :278:17
      automatic logic            _GEN_13;	// src/main/scala/RayTrace.scala:358:29
      automatic logic            _GEN_14 = _GEN_0 | _GEN_1 | _GEN_2;	// src/main/scala/RayTrace.scala:206:25, :278:17
      automatic logic            _GEN_15 = _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3;	// src/main/scala/RayTrace.scala:184:26, :278:17
      automatic logic [15:0]     _oc_result_value_T_20;	// src/main/scala/Fixed.scala:32:39
      automatic logic [15:0]     _oc_result_value_T_26;	// src/main/scala/Fixed.scala:32:39
      automatic logic [15:0]     _oc_result_value_T_32;	// src/main/scala/Fixed.scala:32:39
      automatic logic [22:0]     _GEN_16;	// src/main/scala/Fixed.scala:38:37
      automatic logic [22:0]     _GEN_17;	// src/main/scala/Fixed.scala:38:37
      automatic logic [22:0]     _GEN_18;	// src/main/scala/Fixed.scala:38:37
      automatic logic [22:0]     _a_temp_product_T_17;	// src/main/scala/Fixed.scala:38:37
      automatic logic [22:0]     _a_temp_product_T_14;	// src/main/scala/Fixed.scala:38:37
      automatic logic [22:0]     _a_temp_product_T_11;	// src/main/scala/Fixed.scala:38:37
      automatic logic [14:0]     _a_temp_result_value_T_26;	// src/main/scala/Fixed.scala:26:39
      automatic logic [22:0]     _b_temp_product_T_17;	// src/main/scala/Fixed.scala:38:37
      automatic logic [22:0]     _b_temp_product_T_14;	// src/main/scala/Fixed.scala:38:37
      automatic logic [22:0]     _b_temp_product_T_11;	// src/main/scala/Fixed.scala:38:37
      automatic logic [14:0]     _b_temp_result_value_T_26;	// src/main/scala/Fixed.scala:26:39
      automatic logic [23:0]     _GEN_19;	// src/main/scala/Fixed.scala:38:37
      automatic logic [23:0]     _GEN_20;	// src/main/scala/Fixed.scala:38:37
      automatic logic [23:0]     _GEN_21;	// src/main/scala/Fixed.scala:38:37
      automatic logic [23:0]     _c_temp_product_T_17;	// src/main/scala/Fixed.scala:38:37
      automatic logic [23:0]     _c_temp_product_T_14;	// src/main/scala/Fixed.scala:38:37
      automatic logic [23:0]     _c_temp_product_T_11;	// src/main/scala/Fixed.scala:38:37
      automatic logic [15:0]     _c_result_value_T_8;	// src/main/scala/Fixed.scala:32:39
      automatic logic [23:0]     _GEN_22;	// src/main/scala/Fixed.scala:38:37
      automatic logic [23:0]     _discriminant_product_T_19;	// src/main/scala/Fixed.scala:38:37
      automatic logic [23:0]     _discriminant_product_T_12;	// src/main/scala/Fixed.scala:38:37
      automatic logic [15:0]     _discriminant_result_value_T_16;	// src/main/scala/Fixed.scala:32:39
      automatic logic            discPositive_1;	// src/main/scala/RayTrace.scala:227:50
      automatic logic [15:0]     _GEN_23;	// src/main/scala/Fixed.scala:52:22, src/main/scala/RayTrace.scala:227:50
      automatic logic [15:0]     _GEN_24;	// src/main/scala/Fixed.scala:32:39
      automatic logic [15:0]     _t1_result_value_T_22;	// src/main/scala/Fixed.scala:32:39
      automatic logic [24:0]     _GEN_25;	// src/main/scala/Fixed.scala:46:31
      automatic logic [24:0]     _t1_result_value_T_28;	// src/main/scala/Fixed.scala:46:31
      automatic logic [15:0]     _t2_result_value_T_22;	// src/main/scala/Fixed.scala:26:39
      automatic logic [24:0]     _t2_result_value_T_28;	// src/main/scala/Fixed.scala:46:31
      automatic logic            _GEN_26;	// src/main/scala/Fixed.scala:69:47
      automatic logic            _GEN_27;	// src/main/scala/Fixed.scala:69:47
      automatic logic            _GEN_28;	// src/main/scala/RayTrace.scala:178:22, :394:25, :396:15, :397:58, :398:15
      automatic logic [7:0][2:0] _GEN_29;	// src/main/scala/RayTrace.scala:178:22, :278:17, :280:22, :308:13, :336:13, :340:24, :373:36, :394:25, :423:13, :440:67
      automatic logic [7:0][6:0] _GEN_30;	// src/main/scala/RayTrace.scala:180:23, :278:17, :306:14
      automatic logic [7:0][5:0] _GEN_31;	// src/main/scala/RayTrace.scala:181:23, :278:17, :307:14
      _GEN_13 = closestT_value < 16'h7FFF;	// <stdin>:94:35, src/main/scala/RayTrace.scala:199:25, :358:29
      _oc_result_value_T_20 = shadowRay_origin_x_value - io_sphereData_center_x_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:184:26
      _oc_result_value_T_26 = shadowRay_origin_y_value - io_sphereData_center_y_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:184:26
      _oc_result_value_T_32 = shadowRay_origin_z_value - io_sphereData_center_z_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:184:26
      _GEN_16 = {{7{shadowRay_dir_x_value[15]}}, shadowRay_dir_x_value};	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:184:26
      _GEN_17 = {{7{shadowRay_dir_y_value[15]}}, shadowRay_dir_y_value};	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:184:26
      _GEN_18 = {{7{shadowRay_dir_z_value[15]}}, shadowRay_dir_z_value};	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:184:26
      _a_temp_product_T_17 = _GEN_18 * _GEN_18;	// src/main/scala/Fixed.scala:38:37
      _a_temp_product_T_14 = _GEN_17 * _GEN_17;	// src/main/scala/Fixed.scala:38:37
      _a_temp_product_T_11 = _GEN_16 * _GEN_16;	// src/main/scala/Fixed.scala:38:37
      _a_temp_result_value_T_26 =
        _a_temp_product_T_11[22:8] + _a_temp_product_T_14[22:8]
        + _a_temp_product_T_17[22:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
      _b_temp_product_T_17 =
        {{7{_oc_result_value_T_32[15]}}, _oc_result_value_T_32} * _GEN_18;	// src/main/scala/Fixed.scala:32:39, :38:37
      _b_temp_product_T_14 =
        {{7{_oc_result_value_T_26[15]}}, _oc_result_value_T_26} * _GEN_17;	// src/main/scala/Fixed.scala:32:39, :38:37
      _b_temp_product_T_11 =
        {{7{_oc_result_value_T_20[15]}}, _oc_result_value_T_20} * _GEN_16;	// src/main/scala/Fixed.scala:32:39, :38:37
      _b_temp_result_value_T_26 =
        _b_temp_product_T_11[22:8] + _b_temp_product_T_14[22:8]
        + _b_temp_product_T_17[22:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
      _GEN_19 = {{8{_oc_result_value_T_20[15]}}, _oc_result_value_T_20};	// src/main/scala/Fixed.scala:32:39, :38:37
      _GEN_20 = {{8{_oc_result_value_T_26[15]}}, _oc_result_value_T_26};	// src/main/scala/Fixed.scala:32:39, :38:37
      _GEN_21 = {{8{_oc_result_value_T_32[15]}}, _oc_result_value_T_32};	// src/main/scala/Fixed.scala:32:39, :38:37
      _c_temp_product_T_17 = _GEN_21 * _GEN_21;	// src/main/scala/Fixed.scala:38:37
      _c_temp_product_T_14 = _GEN_20 * _GEN_20;	// src/main/scala/Fixed.scala:38:37
      _c_temp_product_T_11 = _GEN_19 * _GEN_19;	// src/main/scala/Fixed.scala:38:37
      _c_result_value_T_8 =
        _c_temp_product_T_11[23:8] + _c_temp_product_T_14[23:8]
        + _c_temp_product_T_17[23:8] - io_sphereData_radiusSq_value;	// src/main/scala/Fixed.scala:26:39, :32:39, :38:{37,57}, :39:18
      _GEN_22 = {{8{_b_temp_result_value_T_26[14]}}, _b_temp_result_value_T_26, 1'h0};	// src/main/scala/Fixed.scala:26:39, :38:37, src/main/scala/RayTrace.scala:227:50
      _discriminant_product_T_19 =
        {{8{_a_temp_result_value_T_26[13]}}, _a_temp_result_value_T_26[13:0], 2'h0}
        * {{8{_c_result_value_T_8[15]}}, _c_result_value_T_8};	// src/main/scala/Fixed.scala:26:39, :32:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:197:25
      _discriminant_product_T_12 = _GEN_22 * _GEN_22;	// src/main/scala/Fixed.scala:38:37
      _discriminant_result_value_T_16 =
        _discriminant_product_T_12[23:8] - _discriminant_product_T_19[23:8];	// src/main/scala/Fixed.scala:32:39, :38:{37,57}, :39:18
      discPositive_1 = $signed(_discriminant_result_value_T_16) > 16'sh0;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:183:40, :227:50
      _GEN_23 = {_b_temp_result_value_T_26, 1'h0};	// src/main/scala/Fixed.scala:26:39, :52:22, src/main/scala/RayTrace.scala:227:50
      _GEN_24 = {1'h0, _discriminant_result_value_T_16[15:1]};	// src/main/scala/Fixed.scala:32:39, :58:39, src/main/scala/RayTrace.scala:227:50
      _t1_result_value_T_22 = 16'h0 - _GEN_23 - _GEN_24;	// src/main/scala/Fixed.scala:32:39, :52:22, src/main/scala/RayTrace.scala:183:40, :227:50
      _GEN_25 = {{9{_a_temp_result_value_T_26[14]}}, _a_temp_result_value_T_26, 1'h0};	// src/main/scala/Fixed.scala:26:39, :46:31, src/main/scala/RayTrace.scala:227:50
      _t1_result_value_T_28 =
        $signed({_t1_result_value_T_22[15], _t1_result_value_T_22, 8'h0})
        / $signed(_GEN_25);	// src/main/scala/Fixed.scala:32:39, :46:31, src/main/scala/RayTrace.scala:200:27
      _t2_result_value_T_22 = 16'h0 - _GEN_23 + _GEN_24;	// src/main/scala/Fixed.scala:26:39, :32:39, :52:22, src/main/scala/RayTrace.scala:183:40, :227:50
      _t2_result_value_T_28 =
        $signed({_t2_result_value_T_22[15], _t2_result_value_T_22, 8'h0})
        / $signed(_GEN_25);	// src/main/scala/Fixed.scala:26:39, :46:31, src/main/scala/RayTrace.scala:200:27
      _GEN_26 = $signed(_t1_result_value_T_28[15:0]) > 16'sh0;	// src/main/scala/Fixed.scala:46:{18,31,51}, :69:47, src/main/scala/RayTrace.scala:183:40
      _GEN_27 = $signed(_t2_result_value_T_28[15:0]) > 16'sh0;	// src/main/scala/Fixed.scala:46:{18,31,51}, :69:47, src/main/scala/RayTrace.scala:183:40
      _GEN_28 =
        {5'h0, shadowSphereIdx} != closestObj & discPositive_1 & (_GEN_26 | _GEN_27)
        & $signed(discPositive_1
                    ? (_GEN_26
                         ? _t1_result_value_T_28[15:0]
                         : _GEN_27 ? _t2_result_value_T_28[15:0] : 16'h0)
                    : 16'h0) > 16'sh0 | (&shadowSphereIdx);	// src/main/scala/Fixed.scala:46:{18,31,51}, :69:47, :80:16, src/main/scala/RayTrace.scala:131:7, :178:22, :183:40, :196:32, :200:27, :227:50, :229:24, :234:23, :235:13, :237:29, :392:{42,71}, :394:25, :396:15, :397:{34,58}, :398:15
      _GEN_29 =
        {{{1'h0, ~_GEN_11, 1'h0}},
         {3'h4},
         {_GEN_28 ? 3'h6 : state},
         {3'h5},
         {allTested ? (_GEN_13 ? 3'h4 : 3'h7) : state},
         {3'h3},
         {3'h2},
         {io_start ? 3'h1 : state}};	// src/main/scala/RayTrace.scala:178:22, :203:26, :227:50, :272:30, :278:17, :280:22, :281:15, :308:13, :336:13, :340:24, :352:24, :358:{29,51}, :364:17, :367:17, :373:36, :394:25, :396:15, :397:58, :398:15, :423:13, :440:{37,67}, :441:15, :443:44
      state <= _GEN_29[state];	// src/main/scala/RayTrace.scala:178:22, :278:17, :280:22, :308:13, :336:13, :340:24, :373:36, :394:25, :423:13, :440:67
      _GEN_30 =
        {{_GEN_7 | ~(&state) | _GEN_11 ? pixelX : _GEN_10 ? 7'h0 : pixelX + 7'h1},
         {pixelX},
         {pixelX},
         {pixelX},
         {pixelX},
         {pixelX},
         {7'h0},
         {pixelX}};	// src/main/scala/RayTrace.scala:178:22, :180:23, :274:16, :278:17, :306:14, :440:{19,37}, :443:44, :444:16, :448:{16,26}
      pixelX <= _GEN_30[state];	// src/main/scala/RayTrace.scala:178:22, :180:23, :278:17, :306:14
      _GEN_31 =
        {{_GEN_7 | ~(&state) | _GEN_11 | ~_GEN_10 ? pixelY : pixelY + 6'h1},
         {pixelY},
         {pixelY},
         {pixelY},
         {pixelY},
         {pixelY},
         {6'h0},
         {pixelY}};	// src/main/scala/RayTrace.scala:178:22, :181:23, :274:16, :278:17, :307:14, :440:{19,37,67}, :443:44, :445:26
      pixelY <= _GEN_31[state];	// src/main/scala/RayTrace.scala:178:22, :181:23, :278:17, :307:14
      if (_GEN_12 | ~_GEN_2) begin	// src/main/scala/RayTrace.scala:183:27, :278:17
      end
      else begin	// src/main/scala/RayTrace.scala:183:27, :278:17
        automatic logic [15:0] _uCentered_result_value_T_1;	// src/main/scala/Fixed.scala:32:39
        automatic logic [15:0] _vCentered_result_value_T_1;	// src/main/scala/Fixed.scala:32:39
        automatic logic [23:0] _rightComp_product_T_2;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_32;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _upComp_product_T_2;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_33;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _upComp_product_T_5;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _rightComp_product_T_5;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _dir_result_value_T_20;	// src/main/scala/Fixed.scala:26:39
        automatic logic [23:0] _upComp_product_T_8;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _rightComp_product_T_8;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _dir_result_value_T_26;	// src/main/scala/Fixed.scala:26:39
        automatic logic [23:0] _upComp_product_T_11;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _rightComp_product_T_11;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _dir_result_value_T_32;	// src/main/scala/Fixed.scala:26:39
        automatic logic [23:0] _GEN_34;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_35;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_36;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _dirNorm_len_temp_product_T_8;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _dirNorm_len_temp_product_T_5;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _dirNorm_len_temp_product_T_2;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _dirNorm_len_temp_result_value_T_11;	// src/main/scala/Fixed.scala:26:39
        automatic logic [23:0] _dirNorm_len_div_value_T_1;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _dirNorm_len_sum_value_T;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [23:0] _dirNorm_len_div_value_T_3;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _dirNorm_len_sum_value_T_2;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [23:0] _dirNorm_len_div_value_T_5;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _dirNorm_len_sum_value_T_4;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [23:0] _dirNorm_len_div_value_T_7;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _dirNorm_len_sum_value_T_6;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [23:0] _dirNorm_len_div_value_T_9;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _dirNorm_len_sum_value_T_8;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [24:0] _GEN_37;	// src/main/scala/Fixed.scala:46:31
        automatic logic [24:0] _dirNorm_result_value_T_1;	// src/main/scala/Fixed.scala:46:31
        automatic logic [24:0] _dirNorm_result_value_T_4;	// src/main/scala/Fixed.scala:46:31
        automatic logic [24:0] _dirNorm_result_value_T_7;	// src/main/scala/Fixed.scala:46:31
        _uCentered_result_value_T_1 = {1'h0, {pixelX, 8'h0} / 15'h50} - 16'h80;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:180:23, :200:27, :227:50, :315:{26,38}
        _vCentered_result_value_T_1 = 16'h80 - {2'h0, {pixelY, 8'h0} / 14'h28};	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:181:23, :197:25, :200:27, :316:{26,38}
        _rightComp_product_T_2 =
          {{8{_uCentered_result_value_T_1[15]}}, _uCentered_result_value_T_1}
          * {{8{screenWidth_value[15]}}, screenWidth_value};	// src/main/scala/Fixed.scala:32:39, :38:37, src/main/scala/RayTrace.scala:192:28
        _GEN_32 = {{8{_rightComp_product_T_2[23]}}, _rightComp_product_T_2[23:8]};	// src/main/scala/Fixed.scala:38:{37,57}, :39:18
        _upComp_product_T_2 =
          {{8{_vCentered_result_value_T_1[15]}}, _vCentered_result_value_T_1}
          * {{8{screenHeight_value[15]}}, screenHeight_value};	// src/main/scala/Fixed.scala:32:39, :38:37, src/main/scala/RayTrace.scala:193:29
        _GEN_33 = {{8{_upComp_product_T_2[23]}}, _upComp_product_T_2[23:8]};	// src/main/scala/Fixed.scala:38:{37,57}, :39:18
        _upComp_product_T_5 = {{8{cameraUp_x_value[15]}}, cameraUp_x_value} * _GEN_33;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:191:25
        _rightComp_product_T_5 =
          {{8{cameraRight_x_value[15]}}, cameraRight_x_value} * _GEN_32;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:190:28
        _dir_result_value_T_20 =
          cameraForward_x_value + _rightComp_product_T_5[23:8]
          + _upComp_product_T_5[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:189:30
        _upComp_product_T_8 = {{8{cameraUp_y_value[15]}}, cameraUp_y_value} * _GEN_33;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:191:25
        _rightComp_product_T_8 =
          {{8{cameraRight_y_value[15]}}, cameraRight_y_value} * _GEN_32;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:190:28
        _dir_result_value_T_26 =
          cameraForward_y_value + _rightComp_product_T_8[23:8]
          + _upComp_product_T_8[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:189:30
        _upComp_product_T_11 = {{8{cameraUp_z_value[15]}}, cameraUp_z_value} * _GEN_33;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:191:25
        _rightComp_product_T_11 =
          {{8{cameraRight_z_value[15]}}, cameraRight_z_value} * _GEN_32;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:190:28
        _dir_result_value_T_32 =
          cameraForward_z_value + _rightComp_product_T_11[23:8]
          + _upComp_product_T_11[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:189:30
        _GEN_34 = {{8{_dir_result_value_T_20[15]}}, _dir_result_value_T_20};	// src/main/scala/Fixed.scala:26:39, :38:37
        _GEN_35 = {{8{_dir_result_value_T_26[15]}}, _dir_result_value_T_26};	// src/main/scala/Fixed.scala:26:39, :38:37
        _GEN_36 = {{8{_dir_result_value_T_32[15]}}, _dir_result_value_T_32};	// src/main/scala/Fixed.scala:26:39, :38:37
        _dirNorm_len_temp_product_T_8 = _GEN_36 * _GEN_36;	// src/main/scala/Fixed.scala:38:37
        _dirNorm_len_temp_product_T_5 = _GEN_35 * _GEN_35;	// src/main/scala/Fixed.scala:38:37
        _dirNorm_len_temp_product_T_2 = _GEN_34 * _GEN_34;	// src/main/scala/Fixed.scala:38:37
        _dirNorm_len_temp_result_value_T_11 =
          _dirNorm_len_temp_product_T_2[23:8] + _dirNorm_len_temp_product_T_5[23:8]
          + _dirNorm_len_temp_product_T_8[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
        _dirNorm_len_div_value_T_1 =
          {_dirNorm_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _dirNorm_len_temp_result_value_T_11[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :78:{31,44}, :200:27
        _dirNorm_len_sum_value_T =
          {1'h0, _dirNorm_len_temp_result_value_T_11[15:1]}
          + ((|(_dirNorm_len_temp_result_value_T_11[15:1]))
               ? _dirNorm_len_div_value_T_1[15:0]
               : _dirNorm_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :77:{27,34}, :78:{19,44}, :80:19, :84:35, :227:50
        _dirNorm_len_div_value_T_3 =
          {_dirNorm_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _dirNorm_len_sum_value_T[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        _dirNorm_len_sum_value_T_2 =
          {1'h0, _dirNorm_len_sum_value_T[15:1]}
          + ((|(_dirNorm_len_sum_value_T[15:1]))
               ? _dirNorm_len_div_value_T_3[15:0]
               : _dirNorm_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        _dirNorm_len_div_value_T_5 =
          {_dirNorm_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _dirNorm_len_sum_value_T_2[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        _dirNorm_len_sum_value_T_4 =
          {1'h0, _dirNorm_len_sum_value_T_2[15:1]}
          + ((|(_dirNorm_len_sum_value_T_2[15:1]))
               ? _dirNorm_len_div_value_T_5[15:0]
               : _dirNorm_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        _dirNorm_len_div_value_T_7 =
          {_dirNorm_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _dirNorm_len_sum_value_T_4[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        _dirNorm_len_sum_value_T_6 =
          {1'h0, _dirNorm_len_sum_value_T_4[15:1]}
          + ((|(_dirNorm_len_sum_value_T_4[15:1]))
               ? _dirNorm_len_div_value_T_7[15:0]
               : _dirNorm_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        _dirNorm_len_div_value_T_9 =
          {_dirNorm_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _dirNorm_len_sum_value_T_6[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        _dirNorm_len_sum_value_T_8 =
          {1'h0, _dirNorm_len_sum_value_T_6[15:1]}
          + ((|(_dirNorm_len_sum_value_T_6[15:1]))
               ? _dirNorm_len_div_value_T_9[15:0]
               : _dirNorm_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        _GEN_37 = {10'h0, _dirNorm_len_sum_value_T_8[15:1]};	// src/main/scala/Fixed.scala:46:31, src/main/scala/RayTrace.scala:84:35, :87:39
        currentRay_origin_x_value <= io_cameraPos_x_value;	// src/main/scala/RayTrace.scala:183:27
        currentRay_origin_y_value <= io_cameraPos_y_value;	// src/main/scala/RayTrace.scala:183:27
        currentRay_origin_z_value <= io_cameraPos_z_value;	// src/main/scala/RayTrace.scala:183:27
        _dirNorm_result_value_T_1 =
          $signed({_dir_result_value_T_20[15], _dir_result_value_T_20, 8'h0})
          / $signed(_GEN_37);	// src/main/scala/Fixed.scala:26:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        currentRay_dir_x_value <=
          (|(_dirNorm_len_sum_value_T_8[15:1]))
            ? _dirNorm_result_value_T_1[15:0]
            : _dir_result_value_T_20;	// src/main/scala/Fixed.scala:26:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :183:27
        _dirNorm_result_value_T_4 =
          $signed({_dir_result_value_T_26[15], _dir_result_value_T_26, 8'h0})
          / $signed(_GEN_37);	// src/main/scala/Fixed.scala:26:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        currentRay_dir_y_value <=
          (|(_dirNorm_len_sum_value_T_8[15:1]))
            ? _dirNorm_result_value_T_4[15:0]
            : _dir_result_value_T_26;	// src/main/scala/Fixed.scala:26:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :183:27
        _dirNorm_result_value_T_7 =
          $signed({_dir_result_value_T_32[15], _dir_result_value_T_32, 8'h0})
          / $signed(_GEN_37);	// src/main/scala/Fixed.scala:26:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        currentRay_dir_z_value <=
          (|(_dirNorm_len_sum_value_T_8[15:1]))
            ? _dirNorm_result_value_T_7[15:0]
            : _dir_result_value_T_32;	// src/main/scala/Fixed.scala:26:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :183:27
      end
      if (_GEN_15 | ~_GEN_4) begin	// src/main/scala/RayTrace.scala:184:26, :278:17
      end
      else begin	// src/main/scala/RayTrace.scala:184:26, :278:17
        automatic logic [15:0] _lightDir_result_value_T_2;	// src/main/scala/Fixed.scala:32:39
        automatic logic [15:0] _lightDir_result_value_T_8;	// src/main/scala/Fixed.scala:32:39
        automatic logic [15:0] _lightDir_result_value_T_14;	// src/main/scala/Fixed.scala:32:39
        automatic logic [23:0] _GEN_38;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_39;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_40;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _lightDir_len_temp_product_T_8;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _lightDir_len_temp_product_T_5;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _lightDir_len_temp_product_T_2;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _lightDir_len_temp_result_value_T_11;	// src/main/scala/Fixed.scala:26:39
        automatic logic [23:0] _lightDir_len_div_value_T_1;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _lightDir_len_sum_value_T;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [23:0] _lightDir_len_div_value_T_3;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _lightDir_len_sum_value_T_2;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [23:0] _lightDir_len_div_value_T_5;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _lightDir_len_sum_value_T_4;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [23:0] _lightDir_len_div_value_T_7;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _lightDir_len_sum_value_T_6;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [23:0] _lightDir_len_div_value_T_9;	// src/main/scala/RayTrace.scala:78:44
        automatic logic [15:0] _lightDir_len_sum_value_T_8;	// src/main/scala/RayTrace.scala:84:35
        automatic logic [24:0] _GEN_41;	// src/main/scala/Fixed.scala:46:31
        automatic logic [24:0] _lightDir_result_value_T_19;	// src/main/scala/Fixed.scala:46:31
        automatic logic [24:0] _lightDir_result_value_T_22;	// src/main/scala/Fixed.scala:46:31
        automatic logic [24:0] _lightDir_result_value_T_25;	// src/main/scala/Fixed.scala:46:31
        _lightDir_result_value_T_2 = io_lightData_position_x_value - hitPoint_x_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:206:25
        _lightDir_result_value_T_8 = io_lightData_position_y_value - hitPoint_y_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:206:25
        _lightDir_result_value_T_14 = io_lightData_position_z_value - hitPoint_z_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:206:25
        _GEN_38 = {{8{_lightDir_result_value_T_2[15]}}, _lightDir_result_value_T_2};	// src/main/scala/Fixed.scala:32:39, :38:37
        _GEN_39 = {{8{_lightDir_result_value_T_8[15]}}, _lightDir_result_value_T_8};	// src/main/scala/Fixed.scala:32:39, :38:37
        _GEN_40 = {{8{_lightDir_result_value_T_14[15]}}, _lightDir_result_value_T_14};	// src/main/scala/Fixed.scala:32:39, :38:37
        _lightDir_len_temp_product_T_8 = _GEN_40 * _GEN_40;	// src/main/scala/Fixed.scala:38:37
        _lightDir_len_temp_product_T_5 = _GEN_39 * _GEN_39;	// src/main/scala/Fixed.scala:38:37
        _lightDir_len_temp_product_T_2 = _GEN_38 * _GEN_38;	// src/main/scala/Fixed.scala:38:37
        _lightDir_len_temp_result_value_T_11 =
          _lightDir_len_temp_product_T_2[23:8] + _lightDir_len_temp_product_T_5[23:8]
          + _lightDir_len_temp_product_T_8[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
        _lightDir_len_div_value_T_1 =
          {_lightDir_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _lightDir_len_temp_result_value_T_11[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :78:{31,44}, :200:27
        _lightDir_len_sum_value_T =
          {1'h0, _lightDir_len_temp_result_value_T_11[15:1]}
          + ((|(_lightDir_len_temp_result_value_T_11[15:1]))
               ? _lightDir_len_div_value_T_1[15:0]
               : _lightDir_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :77:{27,34}, :78:{19,44}, :80:19, :84:35, :227:50
        _lightDir_len_div_value_T_3 =
          {_lightDir_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _lightDir_len_sum_value_T[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        _lightDir_len_sum_value_T_2 =
          {1'h0, _lightDir_len_sum_value_T[15:1]}
          + ((|(_lightDir_len_sum_value_T[15:1]))
               ? _lightDir_len_div_value_T_3[15:0]
               : _lightDir_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        _lightDir_len_div_value_T_5 =
          {_lightDir_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _lightDir_len_sum_value_T_2[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        _lightDir_len_sum_value_T_4 =
          {1'h0, _lightDir_len_sum_value_T_2[15:1]}
          + ((|(_lightDir_len_sum_value_T_2[15:1]))
               ? _lightDir_len_div_value_T_5[15:0]
               : _lightDir_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        _lightDir_len_div_value_T_7 =
          {_lightDir_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _lightDir_len_sum_value_T_4[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        _lightDir_len_sum_value_T_6 =
          {1'h0, _lightDir_len_sum_value_T_4[15:1]}
          + ((|(_lightDir_len_sum_value_T_4[15:1]))
               ? _lightDir_len_div_value_T_7[15:0]
               : _lightDir_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        _lightDir_len_div_value_T_9 =
          {_lightDir_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _lightDir_len_sum_value_T_6[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        _lightDir_len_sum_value_T_8 =
          {1'h0, _lightDir_len_sum_value_T_6[15:1]}
          + ((|(_lightDir_len_sum_value_T_6[15:1]))
               ? _lightDir_len_div_value_T_9[15:0]
               : _lightDir_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        _GEN_41 = {10'h0, _lightDir_len_sum_value_T_8[15:1]};	// src/main/scala/Fixed.scala:46:31, src/main/scala/RayTrace.scala:84:35, :87:39
        shadowRay_origin_x_value <= hitPoint_x_value;	// src/main/scala/RayTrace.scala:184:26, :206:25
        shadowRay_origin_y_value <= hitPoint_y_value;	// src/main/scala/RayTrace.scala:184:26, :206:25
        shadowRay_origin_z_value <= hitPoint_z_value;	// src/main/scala/RayTrace.scala:184:26, :206:25
        _lightDir_result_value_T_19 =
          $signed({_lightDir_result_value_T_2[15], _lightDir_result_value_T_2, 8'h0})
          / $signed(_GEN_41);	// src/main/scala/Fixed.scala:32:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        shadowRay_dir_x_value <=
          (|(_lightDir_len_sum_value_T_8[15:1]))
            ? _lightDir_result_value_T_19[15:0]
            : _lightDir_result_value_T_2;	// src/main/scala/Fixed.scala:32:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :184:26
        _lightDir_result_value_T_22 =
          $signed({_lightDir_result_value_T_8[15], _lightDir_result_value_T_8, 8'h0})
          / $signed(_GEN_41);	// src/main/scala/Fixed.scala:32:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        shadowRay_dir_y_value <=
          (|(_lightDir_len_sum_value_T_8[15:1]))
            ? _lightDir_result_value_T_22[15:0]
            : _lightDir_result_value_T_8;	// src/main/scala/Fixed.scala:32:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :184:26
        _lightDir_result_value_T_25 =
          $signed({_lightDir_result_value_T_14[15], _lightDir_result_value_T_14, 8'h0})
          / $signed(_GEN_41);	// src/main/scala/Fixed.scala:32:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        shadowRay_dir_z_value <=
          (|(_lightDir_len_sum_value_T_8[15:1]))
            ? _lightDir_result_value_T_25[15:0]
            : _lightDir_result_value_T_14;	// src/main/scala/Fixed.scala:32:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :184:26
      end
      if (_GEN_12 | ~(_GEN_2 | ~(~_GEN_3 | ~allTested | _GEN_13))) begin	// src/main/scala/Fixed.scala:80:16, src/main/scala/RayTrace.scala:183:27, :186:33, :203:26, :278:17, :340:{12,24}, :358:29
      end
      else	// src/main/scala/RayTrace.scala:186:33, :278:17
        currentIntensity_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :186:33
      if (_GEN_0 | ~_GEN_1) begin	// src/main/scala/RayTrace.scala:189:30, :193:29, :278:17
      end
      else begin	// src/main/scala/RayTrace.scala:193:29, :278:17
        automatic logic [23:0] _GEN_42 =
          {{8{io_cameraDir_x_value[15]}}, io_cameraDir_x_value};	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_43 =
          {{8{io_cameraDir_y_value[15]}}, io_cameraDir_y_value};	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_44 =
          {{8{io_cameraDir_z_value[15]}}, io_cameraDir_z_value};	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _forward_len_temp_product_T_8 = _GEN_44 * _GEN_44;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _forward_len_temp_product_T_5 = _GEN_43 * _GEN_43;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _forward_len_temp_product_T_2 = _GEN_42 * _GEN_42;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _forward_len_temp_result_value_T_11 =
          _forward_len_temp_product_T_2[23:8] + _forward_len_temp_product_T_5[23:8]
          + _forward_len_temp_product_T_8[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
        automatic logic [23:0] _forward_len_div_value_T_1 =
          {_forward_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _forward_len_temp_result_value_T_11[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :78:{31,44}, :200:27
        automatic logic [15:0] _forward_len_sum_value_T =
          {1'h0, _forward_len_temp_result_value_T_11[15:1]}
          + ((|(_forward_len_temp_result_value_T_11[15:1]))
               ? _forward_len_div_value_T_1[15:0]
               : _forward_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :77:{27,34}, :78:{19,44}, :80:19, :84:35, :227:50
        automatic logic [23:0] _forward_len_div_value_T_3 =
          {_forward_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _forward_len_sum_value_T[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _forward_len_sum_value_T_2 =
          {1'h0, _forward_len_sum_value_T[15:1]}
          + ((|(_forward_len_sum_value_T[15:1]))
               ? _forward_len_div_value_T_3[15:0]
               : _forward_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _forward_len_div_value_T_5 =
          {_forward_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _forward_len_sum_value_T_2[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _forward_len_sum_value_T_4 =
          {1'h0, _forward_len_sum_value_T_2[15:1]}
          + ((|(_forward_len_sum_value_T_2[15:1]))
               ? _forward_len_div_value_T_5[15:0]
               : _forward_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _forward_len_div_value_T_7 =
          {_forward_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _forward_len_sum_value_T_4[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _forward_len_sum_value_T_6 =
          {1'h0, _forward_len_sum_value_T_4[15:1]}
          + ((|(_forward_len_sum_value_T_4[15:1]))
               ? _forward_len_div_value_T_7[15:0]
               : _forward_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _forward_len_div_value_T_9 =
          {_forward_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _forward_len_sum_value_T_6[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _forward_len_sum_value_T_8 =
          {1'h0, _forward_len_sum_value_T_6[15:1]}
          + ((|(_forward_len_sum_value_T_6[15:1]))
               ? _forward_len_div_value_T_9[15:0]
               : _forward_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [24:0] _GEN_45 = {10'h0, _forward_len_sum_value_T_8[15:1]};	// src/main/scala/Fixed.scala:46:31, src/main/scala/RayTrace.scala:84:35, :87:39
        automatic logic [24:0] _forward_result_value_T_1 =
          $signed({io_cameraDir_x_value[15], io_cameraDir_x_value, 8'h0})
          / $signed(_GEN_45);	// src/main/scala/Fixed.scala:38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        automatic logic [15:0] forward_x_value =
          (|(_forward_len_sum_value_T_8[15:1]))
            ? _forward_result_value_T_1[15:0]
            : io_cameraDir_x_value;	// src/main/scala/Fixed.scala:46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39
        automatic logic [24:0] _forward_result_value_T_4 =
          $signed({io_cameraDir_y_value[15], io_cameraDir_y_value, 8'h0})
          / $signed(_GEN_45);	// src/main/scala/Fixed.scala:38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        automatic logic [15:0] forward_y_value =
          (|(_forward_len_sum_value_T_8[15:1]))
            ? _forward_result_value_T_4[15:0]
            : io_cameraDir_y_value;	// src/main/scala/Fixed.scala:46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39
        automatic logic [24:0] _forward_result_value_T_7 =
          $signed({io_cameraDir_z_value[15], io_cameraDir_z_value, 8'h0})
          / $signed(_GEN_45);	// src/main/scala/Fixed.scala:38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        automatic logic [15:0] forward_z_value =
          (|(_forward_len_sum_value_T_8[15:1]))
            ? _forward_result_value_T_7[15:0]
            : io_cameraDir_z_value;	// src/main/scala/Fixed.scala:46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39
        automatic logic [15:0] _right_result_value_T_20 = 16'h0 - forward_x_value;	// src/main/scala/Fixed.scala:11:41, :32:39, :80:16, src/main/scala/RayTrace.scala:57:27, :62:11, :183:40
        automatic logic [23:0] _GEN_46 = {{8{forward_z_value[15]}}, forward_z_value};	// src/main/scala/Fixed.scala:38:37, :80:16, src/main/scala/RayTrace.scala:57:27, :62:11
        automatic logic [23:0] _GEN_47 =
          {{8{_right_result_value_T_20[15]}}, _right_result_value_T_20};	// src/main/scala/Fixed.scala:11:41, :32:39, :38:37
        automatic logic [23:0] _right_len_temp_product_T_8 = _GEN_47 * _GEN_47;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _right_len_temp_product_T_2 = _GEN_46 * _GEN_46;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _right_len_temp_result_value_T_11 =
          _right_len_temp_product_T_2[23:8] + _right_len_temp_product_T_8[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
        automatic logic [23:0] _right_len_div_value_T_1 =
          {_right_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _right_len_temp_result_value_T_11[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :78:{31,44}, :200:27
        automatic logic [15:0] _right_len_sum_value_T =
          {1'h0, _right_len_temp_result_value_T_11[15:1]}
          + ((|(_right_len_temp_result_value_T_11[15:1]))
               ? _right_len_div_value_T_1[15:0]
               : _right_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :77:{27,34}, :78:{19,44}, :80:19, :84:35, :227:50
        automatic logic [23:0] _right_len_div_value_T_3 =
          {_right_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _right_len_sum_value_T[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _right_len_sum_value_T_2 =
          {1'h0, _right_len_sum_value_T[15:1]}
          + ((|(_right_len_sum_value_T[15:1]))
               ? _right_len_div_value_T_3[15:0]
               : _right_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _right_len_div_value_T_5 =
          {_right_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _right_len_sum_value_T_2[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _right_len_sum_value_T_4 =
          {1'h0, _right_len_sum_value_T_2[15:1]}
          + ((|(_right_len_sum_value_T_2[15:1]))
               ? _right_len_div_value_T_5[15:0]
               : _right_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _right_len_div_value_T_7 =
          {_right_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _right_len_sum_value_T_4[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _right_len_sum_value_T_6 =
          {1'h0, _right_len_sum_value_T_4[15:1]}
          + ((|(_right_len_sum_value_T_4[15:1]))
               ? _right_len_div_value_T_7[15:0]
               : _right_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _right_len_div_value_T_9 =
          {_right_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _right_len_sum_value_T_6[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _right_len_sum_value_T_8 =
          {1'h0, _right_len_sum_value_T_6[15:1]}
          + ((|(_right_len_sum_value_T_6[15:1]))
               ? _right_len_div_value_T_9[15:0]
               : _right_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [24:0] _GEN_48 = {10'h0, _right_len_sum_value_T_8[15:1]};	// src/main/scala/Fixed.scala:46:31, src/main/scala/RayTrace.scala:84:35, :87:39
        automatic logic [24:0] _right_result_value_T_25 =
          $signed({forward_z_value[15], forward_z_value, 8'h0}) / $signed(_GEN_48);	// src/main/scala/Fixed.scala:38:37, :46:31, :80:16, src/main/scala/RayTrace.scala:57:27, :62:11, :200:27
        automatic logic [15:0] right_x_value =
          (|(_right_len_sum_value_T_8[15:1]))
            ? _right_result_value_T_25[15:0]
            : forward_z_value;	// src/main/scala/Fixed.scala:46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39
        automatic logic [24:0] _right_result_value_T_31 =
          $signed({_right_result_value_T_20[15], _right_result_value_T_20, 8'h0})
          / $signed(_GEN_48);	// src/main/scala/Fixed.scala:11:41, :32:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        automatic logic [15:0] right_z_value =
          (|(_right_len_sum_value_T_8[15:1]))
            ? _right_result_value_T_31[15:0]
            : _right_result_value_T_20;	// src/main/scala/Fixed.scala:11:41, :32:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39
        automatic logic [23:0] _GEN_49 = {{8{forward_y_value[15]}}, forward_y_value};	// src/main/scala/Fixed.scala:38:37, :80:16, src/main/scala/RayTrace.scala:57:27, :62:11
        automatic logic [23:0] _GEN_50 = {{8{right_z_value[15]}}, right_z_value};	// src/main/scala/Fixed.scala:38:37, :80:16, src/main/scala/RayTrace.scala:57:27, :62:11
        automatic logic [23:0] _up_product_T_2 = _GEN_49 * _GEN_50;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _GEN_51 = {{8{right_x_value[15]}}, right_x_value};	// src/main/scala/Fixed.scala:38:37, :80:16, src/main/scala/RayTrace.scala:57:27, :62:11
        automatic logic [23:0] _up_product_T_11 =
          {{8{forward_x_value[15]}}, forward_x_value} * _GEN_50;	// src/main/scala/Fixed.scala:38:37, :80:16, src/main/scala/RayTrace.scala:57:27, :62:11
        automatic logic [23:0] _up_product_T_8 = _GEN_46 * _GEN_51;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _up_result_value_T_12 =
          _up_product_T_8[23:8] - _up_product_T_11[23:8];	// src/main/scala/Fixed.scala:32:39, :38:{37,57}, :39:18
        automatic logic [23:0] _up_product_T_17 = _GEN_49 * _GEN_51;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _up_result_value_T_20 = 16'h0 - _up_product_T_17[23:8];	// src/main/scala/Fixed.scala:11:41, :32:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:183:40
        automatic logic [23:0] _GEN_52 =
          {{8{_up_product_T_2[23]}}, _up_product_T_2[23:8]};	// src/main/scala/Fixed.scala:38:{37,57}, :39:18
        automatic logic [23:0] _GEN_53 =
          {{8{_up_result_value_T_12[15]}}, _up_result_value_T_12};	// src/main/scala/Fixed.scala:32:39, :38:37
        automatic logic [23:0] _GEN_54 =
          {{8{_up_result_value_T_20[15]}}, _up_result_value_T_20};	// src/main/scala/Fixed.scala:11:41, :32:39, :38:37
        automatic logic [23:0] _up_len_temp_product_T_8 = _GEN_54 * _GEN_54;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _up_len_temp_product_T_5 = _GEN_53 * _GEN_53;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _up_len_temp_product_T_2 = _GEN_52 * _GEN_52;	// src/main/scala/Fixed.scala:38:37
        automatic logic [15:0] _up_len_temp_result_value_T_11 =
          _up_len_temp_product_T_2[23:8] + _up_len_temp_product_T_5[23:8]
          + _up_len_temp_product_T_8[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
        automatic logic [23:0] _up_len_div_value_T_1 =
          {_up_len_temp_result_value_T_11, 8'h0}
          / {9'h0, _up_len_temp_result_value_T_11[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :78:{31,44}, :200:27
        automatic logic [15:0] _up_len_sum_value_T =
          {1'h0, _up_len_temp_result_value_T_11[15:1]}
          + ((|(_up_len_temp_result_value_T_11[15:1]))
               ? _up_len_div_value_T_1[15:0]
               : _up_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:73:31, :77:{27,34}, :78:{19,44}, :80:19, :84:35, :227:50
        automatic logic [23:0] _up_len_div_value_T_3 =
          {_up_len_temp_result_value_T_11, 8'h0} / {9'h0, _up_len_sum_value_T[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _up_len_sum_value_T_2 =
          {1'h0, _up_len_sum_value_T[15:1]}
          + ((|(_up_len_sum_value_T[15:1]))
               ? _up_len_div_value_T_3[15:0]
               : _up_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _up_len_div_value_T_5 =
          {_up_len_temp_result_value_T_11, 8'h0} / {9'h0, _up_len_sum_value_T_2[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _up_len_sum_value_T_4 =
          {1'h0, _up_len_sum_value_T_2[15:1]}
          + ((|(_up_len_sum_value_T_2[15:1]))
               ? _up_len_div_value_T_5[15:0]
               : _up_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _up_len_div_value_T_7 =
          {_up_len_temp_result_value_T_11, 8'h0} / {9'h0, _up_len_sum_value_T_4[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _up_len_sum_value_T_6 =
          {1'h0, _up_len_sum_value_T_4[15:1]}
          + ((|(_up_len_sum_value_T_4[15:1]))
               ? _up_len_div_value_T_7[15:0]
               : _up_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [23:0] _up_len_div_value_T_9 =
          {_up_len_temp_result_value_T_11, 8'h0} / {9'h0, _up_len_sum_value_T_6[15:1]};	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:78:{31,44}, :84:35, :87:39, :200:27
        automatic logic [15:0] _up_len_sum_value_T_8 =
          {1'h0, _up_len_sum_value_T_6[15:1]}
          + ((|(_up_len_sum_value_T_6[15:1]))
               ? _up_len_div_value_T_9[15:0]
               : _up_len_temp_result_value_T_11);	// src/main/scala/Fixed.scala:26:39, src/main/scala/RayTrace.scala:77:{27,34}, :78:{19,44}, :80:19, :84:35, :87:39, :227:50
        automatic logic [24:0] _GEN_55 = {10'h0, _up_len_sum_value_T_8[15:1]};	// src/main/scala/Fixed.scala:46:31, src/main/scala/RayTrace.scala:84:35, :87:39
        automatic logic [31:0] _fovRad_value_T_1 = {16'h0, io_fov} * 32'h324 / 32'hB4;	// src/main/scala/RayTrace.scala:183:40, :301:{32,44}
        automatic logic [24:0] _up_result_value_T_25 =
          $signed({_up_product_T_2[23], _up_product_T_2[23:8], 8'h0}) / $signed(_GEN_55);	// src/main/scala/Fixed.scala:38:{37,57}, :39:18, :46:31, src/main/scala/RayTrace.scala:200:27
        automatic logic [24:0] _up_result_value_T_28 =
          $signed({_up_result_value_T_12[15], _up_result_value_T_12, 8'h0})
          / $signed(_GEN_55);	// src/main/scala/Fixed.scala:32:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        automatic logic [24:0] _up_result_value_T_31 =
          $signed({_up_result_value_T_20[15], _up_result_value_T_20, 8'h0})
          / $signed(_GEN_55);	// src/main/scala/Fixed.scala:11:41, :32:39, :38:37, :46:31, src/main/scala/RayTrace.scala:200:27
        cameraForward_x_value <= forward_x_value;	// src/main/scala/Fixed.scala:80:16, src/main/scala/RayTrace.scala:57:27, :62:11, :189:30
        cameraForward_y_value <= forward_y_value;	// src/main/scala/Fixed.scala:80:16, src/main/scala/RayTrace.scala:57:27, :62:11, :189:30
        cameraForward_z_value <= forward_z_value;	// src/main/scala/Fixed.scala:80:16, src/main/scala/RayTrace.scala:57:27, :62:11, :189:30
        cameraRight_x_value <= right_x_value;	// src/main/scala/Fixed.scala:80:16, src/main/scala/RayTrace.scala:57:27, :62:11, :190:28
        cameraRight_y_value <= 16'h0;	// src/main/scala/RayTrace.scala:183:40, :190:28
        cameraRight_z_value <= right_z_value;	// src/main/scala/Fixed.scala:80:16, src/main/scala/RayTrace.scala:57:27, :62:11, :190:28
        cameraUp_x_value <=
          (|(_up_len_sum_value_T_8[15:1]))
            ? _up_result_value_T_25[15:0]
            : _up_product_T_2[23:8];	// src/main/scala/Fixed.scala:38:{37,57}, :39:18, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :191:25
        cameraUp_y_value <=
          (|(_up_len_sum_value_T_8[15:1]))
            ? _up_result_value_T_28[15:0]
            : _up_result_value_T_12;	// src/main/scala/Fixed.scala:32:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :191:25
        cameraUp_z_value <=
          (|(_up_len_sum_value_T_8[15:1]))
            ? _up_result_value_T_31[15:0]
            : _up_result_value_T_20;	// src/main/scala/Fixed.scala:11:41, :32:39, :46:{18,31,51}, :80:16, src/main/scala/RayTrace.scala:57:{20,27}, :62:11, :84:35, :87:39, :191:25
        screenWidth_value <= {_fovRad_value_T_1[15:1], 1'h0};	// src/main/scala/Fixed.scala:38:57, :39:18, :58:39, src/main/scala/RayTrace.scala:192:28, :227:50, :301:44
        screenHeight_value <= {1'h0, _fovRad_value_T_1[15:1]};	// src/main/scala/Fixed.scala:58:{18,39}, src/main/scala/RayTrace.scala:193:29, :227:50, :301:44
      end
      if (~_GEN_12) begin	// src/main/scala/RayTrace.scala:183:27, :278:17
        if (_GEN_2) begin	// src/main/scala/RayTrace.scala:278:17
          sphereIdx <= 3'h0;	// src/main/scala/RayTrace.scala:195:26
          closestT_value <= 16'h7FFF;	// <stdin>:94:35, src/main/scala/RayTrace.scala:199:25
          closestObj <= 8'h0;	// src/main/scala/RayTrace.scala:200:27
        end
        else begin	// src/main/scala/RayTrace.scala:278:17
          automatic logic [15:0] _oc_result_value_T_2;	// src/main/scala/Fixed.scala:32:39
          automatic logic [15:0] _oc_result_value_T_8;	// src/main/scala/Fixed.scala:32:39
          automatic logic [15:0] _oc_result_value_T_14;	// src/main/scala/Fixed.scala:32:39
          automatic logic [22:0] _GEN_56;	// src/main/scala/Fixed.scala:38:37
          automatic logic [22:0] _GEN_57;	// src/main/scala/Fixed.scala:38:37
          automatic logic [22:0] _GEN_58;	// src/main/scala/Fixed.scala:38:37
          automatic logic [22:0] _a_temp_product_T_8;	// src/main/scala/Fixed.scala:38:37
          automatic logic [22:0] _a_temp_product_T_5;	// src/main/scala/Fixed.scala:38:37
          automatic logic [22:0] _a_temp_product_T_2;	// src/main/scala/Fixed.scala:38:37
          automatic logic [14:0] _a_temp_result_value_T_11;	// src/main/scala/Fixed.scala:26:39
          automatic logic [22:0] _b_temp_product_T_8;	// src/main/scala/Fixed.scala:38:37
          automatic logic [22:0] _b_temp_product_T_5;	// src/main/scala/Fixed.scala:38:37
          automatic logic [22:0] _b_temp_product_T_2;	// src/main/scala/Fixed.scala:38:37
          automatic logic [14:0] _b_temp_result_value_T_11;	// src/main/scala/Fixed.scala:26:39
          automatic logic [23:0] _GEN_59;	// src/main/scala/Fixed.scala:38:37
          automatic logic [23:0] _GEN_60;	// src/main/scala/Fixed.scala:38:37
          automatic logic [23:0] _GEN_61;	// src/main/scala/Fixed.scala:38:37
          automatic logic [23:0] _c_temp_product_T_8;	// src/main/scala/Fixed.scala:38:37
          automatic logic [23:0] _c_temp_product_T_5;	// src/main/scala/Fixed.scala:38:37
          automatic logic [23:0] _c_temp_product_T_2;	// src/main/scala/Fixed.scala:38:37
          automatic logic [15:0] _c_result_value_T_2;	// src/main/scala/Fixed.scala:32:39
          automatic logic [23:0] _GEN_62;	// src/main/scala/Fixed.scala:38:37
          automatic logic [23:0] _discriminant_product_T_9;	// src/main/scala/Fixed.scala:38:37
          automatic logic [23:0] _discriminant_product_T_2;	// src/main/scala/Fixed.scala:38:37
          automatic logic [15:0] _discriminant_result_value_T_6;	// src/main/scala/Fixed.scala:32:39
          automatic logic        discPositive;	// src/main/scala/RayTrace.scala:227:50
          automatic logic [15:0] _GEN_63;	// src/main/scala/Fixed.scala:52:22, src/main/scala/RayTrace.scala:227:50
          automatic logic [15:0] _GEN_64;	// src/main/scala/Fixed.scala:32:39
          automatic logic [15:0] _t1_result_value_T_7;	// src/main/scala/Fixed.scala:32:39
          automatic logic [24:0] _GEN_65;	// src/main/scala/Fixed.scala:46:31
          automatic logic [24:0] _t1_result_value_T_13;	// src/main/scala/Fixed.scala:46:31
          automatic logic [15:0] _t2_result_value_T_7;	// src/main/scala/Fixed.scala:26:39
          automatic logic [24:0] _t2_result_value_T_13;	// src/main/scala/Fixed.scala:46:31
          automatic logic        _GEN_66;	// src/main/scala/Fixed.scala:69:47
          automatic logic        _GEN_67;	// src/main/scala/Fixed.scala:69:47
          automatic logic [15:0] t_value;	// src/main/scala/Fixed.scala:80:16, src/main/scala/RayTrace.scala:229:24, :234:23
          _oc_result_value_T_2 = currentRay_origin_x_value - io_sphereData_center_x_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:183:27
          _oc_result_value_T_8 = currentRay_origin_y_value - io_sphereData_center_y_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:183:27
          _oc_result_value_T_14 =
            currentRay_origin_z_value - io_sphereData_center_z_value;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:183:27
          _GEN_56 = {{7{currentRay_dir_x_value[15]}}, currentRay_dir_x_value};	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:183:27
          _GEN_57 = {{7{currentRay_dir_y_value[15]}}, currentRay_dir_y_value};	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:183:27
          _GEN_58 = {{7{currentRay_dir_z_value[15]}}, currentRay_dir_z_value};	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:183:27
          _a_temp_product_T_8 = _GEN_58 * _GEN_58;	// src/main/scala/Fixed.scala:38:37
          _a_temp_product_T_5 = _GEN_57 * _GEN_57;	// src/main/scala/Fixed.scala:38:37
          _a_temp_product_T_2 = _GEN_56 * _GEN_56;	// src/main/scala/Fixed.scala:38:37
          _a_temp_result_value_T_11 =
            _a_temp_product_T_2[22:8] + _a_temp_product_T_5[22:8]
            + _a_temp_product_T_8[22:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
          _b_temp_product_T_8 =
            {{7{_oc_result_value_T_14[15]}}, _oc_result_value_T_14} * _GEN_58;	// src/main/scala/Fixed.scala:32:39, :38:37
          _b_temp_product_T_5 =
            {{7{_oc_result_value_T_8[15]}}, _oc_result_value_T_8} * _GEN_57;	// src/main/scala/Fixed.scala:32:39, :38:37
          _b_temp_product_T_2 =
            {{7{_oc_result_value_T_2[15]}}, _oc_result_value_T_2} * _GEN_56;	// src/main/scala/Fixed.scala:32:39, :38:37
          _b_temp_result_value_T_11 =
            _b_temp_product_T_2[22:8] + _b_temp_product_T_5[22:8]
            + _b_temp_product_T_8[22:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18
          _GEN_59 = {{8{_oc_result_value_T_2[15]}}, _oc_result_value_T_2};	// src/main/scala/Fixed.scala:32:39, :38:37
          _GEN_60 = {{8{_oc_result_value_T_8[15]}}, _oc_result_value_T_8};	// src/main/scala/Fixed.scala:32:39, :38:37
          _GEN_61 = {{8{_oc_result_value_T_14[15]}}, _oc_result_value_T_14};	// src/main/scala/Fixed.scala:32:39, :38:37
          _c_temp_product_T_8 = _GEN_61 * _GEN_61;	// src/main/scala/Fixed.scala:38:37
          _c_temp_product_T_5 = _GEN_60 * _GEN_60;	// src/main/scala/Fixed.scala:38:37
          _c_temp_product_T_2 = _GEN_59 * _GEN_59;	// src/main/scala/Fixed.scala:38:37
          _c_result_value_T_2 =
            _c_temp_product_T_2[23:8] + _c_temp_product_T_5[23:8]
            + _c_temp_product_T_8[23:8] - io_sphereData_radiusSq_value;	// src/main/scala/Fixed.scala:26:39, :32:39, :38:{37,57}, :39:18
          _GEN_62 = {{8{_b_temp_result_value_T_11[14]}}, _b_temp_result_value_T_11, 1'h0};	// src/main/scala/Fixed.scala:26:39, :38:37, src/main/scala/RayTrace.scala:227:50
          _discriminant_product_T_9 =
            {{8{_a_temp_result_value_T_11[13]}}, _a_temp_result_value_T_11[13:0], 2'h0}
            * {{8{_c_result_value_T_2[15]}}, _c_result_value_T_2};	// src/main/scala/Fixed.scala:26:39, :32:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:197:25
          _discriminant_product_T_2 = _GEN_62 * _GEN_62;	// src/main/scala/Fixed.scala:38:37
          _discriminant_result_value_T_6 =
            _discriminant_product_T_2[23:8] - _discriminant_product_T_9[23:8];	// src/main/scala/Fixed.scala:32:39, :38:{37,57}, :39:18
          discPositive = $signed(_discriminant_result_value_T_6) > 16'sh0;	// src/main/scala/Fixed.scala:32:39, src/main/scala/RayTrace.scala:183:40, :227:50
          _GEN_63 = {_b_temp_result_value_T_11, 1'h0};	// src/main/scala/Fixed.scala:26:39, :52:22, src/main/scala/RayTrace.scala:227:50
          _GEN_64 = {1'h0, _discriminant_result_value_T_6[15:1]};	// src/main/scala/Fixed.scala:32:39, :58:39, src/main/scala/RayTrace.scala:227:50
          _t1_result_value_T_7 = 16'h0 - _GEN_63 - _GEN_64;	// src/main/scala/Fixed.scala:32:39, :52:22, src/main/scala/RayTrace.scala:183:40, :227:50
          _GEN_65 = {{9{_a_temp_result_value_T_11[14]}}, _a_temp_result_value_T_11, 1'h0};	// src/main/scala/Fixed.scala:26:39, :46:31, src/main/scala/RayTrace.scala:227:50
          _t1_result_value_T_13 =
            $signed({_t1_result_value_T_7[15], _t1_result_value_T_7, 8'h0})
            / $signed(_GEN_65);	// src/main/scala/Fixed.scala:32:39, :46:31, src/main/scala/RayTrace.scala:200:27
          _t2_result_value_T_7 = 16'h0 - _GEN_63 + _GEN_64;	// src/main/scala/Fixed.scala:26:39, :32:39, :52:22, src/main/scala/RayTrace.scala:183:40, :227:50
          _t2_result_value_T_13 =
            $signed({_t2_result_value_T_7[15], _t2_result_value_T_7, 8'h0})
            / $signed(_GEN_65);	// src/main/scala/Fixed.scala:26:39, :46:31, src/main/scala/RayTrace.scala:200:27
          _GEN_66 = $signed(_t1_result_value_T_13[15:0]) > 16'sh0;	// src/main/scala/Fixed.scala:46:{18,31,51}, :69:47, src/main/scala/RayTrace.scala:183:40
          _GEN_67 = $signed(_t2_result_value_T_13[15:0]) > 16'sh0;	// src/main/scala/Fixed.scala:46:{18,31,51}, :69:47, src/main/scala/RayTrace.scala:183:40
          t_value =
            discPositive
              ? (_GEN_66
                   ? _t1_result_value_T_13[15:0]
                   : _GEN_67 ? _t2_result_value_T_13[15:0] : 16'h0)
              : 16'h0;	// src/main/scala/Fixed.scala:46:{18,31,51}, :69:47, :80:16, src/main/scala/RayTrace.scala:183:40, :227:50, :229:24, :234:23, :237:29
          if (~(_GEN_3 & ~allTested) | (&sphereIdx)) begin	// src/main/scala/RayTrace.scala:195:26, :203:26, :278:17, :340:{12,24}, :352:{24,48}
          end
          else	// src/main/scala/RayTrace.scala:195:26, :278:17, :340:24, :352:48
            sphereIdx <= sphereIdx + 3'h1;	// src/main/scala/RayTrace.scala:195:26, :281:15, :355:34
          if (_GEN_3 & ~allTested & discPositive & (_GEN_66 | _GEN_67)
              & t_value < closestT_value & (|t_value)) begin	// src/main/scala/Fixed.scala:69:47, :80:16, src/main/scala/RayTrace.scala:199:25, :203:26, :227:50, :229:24, :234:23, :235:13, :237:29, :278:17, :340:{12,24}, :344:{29,57,71}
            closestT_value <= t_value;	// src/main/scala/Fixed.scala:80:16, src/main/scala/RayTrace.scala:199:25, :229:24, :234:23
            closestObj <= {5'h0, sphereIdx};	// src/main/scala/RayTrace.scala:131:7, :195:26, :200:27, :347:22
          end
        end
        allTested <= ~_GEN_2 & (_GEN_3 & ~allTested & (&sphereIdx) | allTested);	// src/main/scala/RayTrace.scala:183:27, :195:26, :203:26, :278:17, :333:17, :340:{12,24}, :352:{24,48}, :353:21
      end
      if (~_GEN_15) begin	// src/main/scala/RayTrace.scala:184:26, :278:17
        if (_GEN_4)	// src/main/scala/RayTrace.scala:278:17
          shadowSphereIdx <= 3'h0;	// src/main/scala/RayTrace.scala:195:26, :196:32
        else if (~_GEN_5 | _GEN_28) begin	// src/main/scala/RayTrace.scala:178:22, :196:32, :278:17, :394:25, :396:15, :397:58, :398:15
        end
        else	// src/main/scala/RayTrace.scala:196:32, :278:17, :394:25
          shadowSphereIdx <= shadowSphereIdx + 3'h1;	// src/main/scala/RayTrace.scala:196:32, :281:15, :400:44
      end
      if (~_GEN_14) begin	// src/main/scala/RayTrace.scala:206:25, :278:17
        if (_GEN_3) begin	// src/main/scala/RayTrace.scala:278:17
          if (allTested & _GEN_13)	// src/main/scala/RayTrace.scala:197:25, :203:26, :340:24, :358:{29,51}
            lightIdx <= 2'h0;	// src/main/scala/RayTrace.scala:197:25
        end
        else if (_GEN_4 | _GEN_5 | ~_GEN_6) begin	// src/main/scala/RayTrace.scala:197:25, :278:17
        end
        else	// src/main/scala/RayTrace.scala:197:25, :278:17
          lightIdx <= lightIdx + 2'h1;	// src/main/scala/RayTrace.scala:197:25, :281:15, :422:28
      end
      if (_GEN_14 | ~(_GEN_3 & allTested & _GEN_13)) begin	// src/main/scala/RayTrace.scala:203:26, :206:25, :278:17, :340:24, :358:29
      end
      else begin	// src/main/scala/RayTrace.scala:206:25, :278:17
        automatic logic [23:0] _GEN_68;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _nextHitPoint_product_T_2;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _nextHitPoint_product_T_5;	// src/main/scala/Fixed.scala:38:37
        automatic logic [23:0] _nextHitPoint_product_T_8;	// src/main/scala/Fixed.scala:38:37
        _GEN_68 = {{8{closestT_value[15]}}, closestT_value};	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:199:25
        _nextHitPoint_product_T_2 =
          {{8{currentRay_dir_x_value[15]}}, currentRay_dir_x_value} * _GEN_68;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:183:27
        hitPoint_x_value <= currentRay_origin_x_value + _nextHitPoint_product_T_2[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:183:27, :206:25
        _nextHitPoint_product_T_5 =
          {{8{currentRay_dir_y_value[15]}}, currentRay_dir_y_value} * _GEN_68;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:183:27
        hitPoint_y_value <= currentRay_origin_y_value + _nextHitPoint_product_T_5[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:183:27, :206:25
        _nextHitPoint_product_T_8 =
          {{8{currentRay_dir_z_value[15]}}, currentRay_dir_z_value} * _GEN_68;	// src/main/scala/Fixed.scala:38:37, src/main/scala/RayTrace.scala:183:27
        hitPoint_z_value <= currentRay_origin_z_value + _nextHitPoint_product_T_8[23:8];	// src/main/scala/Fixed.scala:26:39, :38:{37,57}, :39:18, src/main/scala/RayTrace.scala:183:27, :206:25
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/RayTrace.scala:131:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/RayTrace.scala:131:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/RayTrace.scala:131:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/RayTrace.scala:131:7
      automatic logic [31:0] _RANDOM[0:17];	// src/main/scala/RayTrace.scala:131:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/RayTrace.scala:131:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/RayTrace.scala:131:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/RayTrace.scala:131:7
        for (logic [4:0] i = 5'h0; i < 5'h12; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/RayTrace.scala:131:7
        end	// src/main/scala/RayTrace.scala:131:7
        state = _RANDOM[5'h0][2:0];	// src/main/scala/RayTrace.scala:131:7, :178:22
        pixelX = _RANDOM[5'h0][9:3];	// src/main/scala/RayTrace.scala:131:7, :178:22, :180:23
        pixelY = _RANDOM[5'h0][15:10];	// src/main/scala/RayTrace.scala:131:7, :178:22, :181:23
        currentRay_origin_x_value = _RANDOM[5'h0][31:16];	// src/main/scala/RayTrace.scala:131:7, :178:22, :183:27
        currentRay_origin_y_value = _RANDOM[5'h1][15:0];	// src/main/scala/RayTrace.scala:131:7, :183:27
        currentRay_origin_z_value = _RANDOM[5'h1][31:16];	// src/main/scala/RayTrace.scala:131:7, :183:27
        currentRay_dir_x_value = _RANDOM[5'h2][15:0];	// src/main/scala/RayTrace.scala:131:7, :183:27
        currentRay_dir_y_value = _RANDOM[5'h2][31:16];	// src/main/scala/RayTrace.scala:131:7, :183:27
        currentRay_dir_z_value = _RANDOM[5'h3][15:0];	// src/main/scala/RayTrace.scala:131:7, :183:27
        shadowRay_origin_x_value = _RANDOM[5'h3][31:16];	// src/main/scala/RayTrace.scala:131:7, :183:27, :184:26
        shadowRay_origin_y_value = _RANDOM[5'h4][15:0];	// src/main/scala/RayTrace.scala:131:7, :184:26
        shadowRay_origin_z_value = _RANDOM[5'h4][31:16];	// src/main/scala/RayTrace.scala:131:7, :184:26
        shadowRay_dir_x_value = _RANDOM[5'h5][15:0];	// src/main/scala/RayTrace.scala:131:7, :184:26
        shadowRay_dir_y_value = _RANDOM[5'h5][31:16];	// src/main/scala/RayTrace.scala:131:7, :184:26
        shadowRay_dir_z_value = _RANDOM[5'h6][15:0];	// src/main/scala/RayTrace.scala:131:7, :184:26
        currentIntensity_value = _RANDOM[5'h6][31:16];	// src/main/scala/RayTrace.scala:131:7, :184:26, :186:33
        cameraForward_x_value = _RANDOM[5'h7][31:16];	// src/main/scala/RayTrace.scala:131:7, :189:30
        cameraForward_y_value = _RANDOM[5'h8][15:0];	// src/main/scala/RayTrace.scala:131:7, :189:30
        cameraForward_z_value = _RANDOM[5'h8][31:16];	// src/main/scala/RayTrace.scala:131:7, :189:30
        cameraRight_x_value = _RANDOM[5'h9][15:0];	// src/main/scala/RayTrace.scala:131:7, :190:28
        cameraRight_y_value = _RANDOM[5'h9][31:16];	// src/main/scala/RayTrace.scala:131:7, :190:28
        cameraRight_z_value = _RANDOM[5'hA][15:0];	// src/main/scala/RayTrace.scala:131:7, :190:28
        cameraUp_x_value = _RANDOM[5'hA][31:16];	// src/main/scala/RayTrace.scala:131:7, :190:28, :191:25
        cameraUp_y_value = _RANDOM[5'hB][15:0];	// src/main/scala/RayTrace.scala:131:7, :191:25
        cameraUp_z_value = _RANDOM[5'hB][31:16];	// src/main/scala/RayTrace.scala:131:7, :191:25
        screenWidth_value = _RANDOM[5'hC][15:0];	// src/main/scala/RayTrace.scala:131:7, :192:28
        screenHeight_value = _RANDOM[5'hC][31:16];	// src/main/scala/RayTrace.scala:131:7, :192:28, :193:29
        sphereIdx = _RANDOM[5'hD][2:0];	// src/main/scala/RayTrace.scala:131:7, :195:26
        shadowSphereIdx = _RANDOM[5'hD][5:3];	// src/main/scala/RayTrace.scala:131:7, :195:26, :196:32
        lightIdx = _RANDOM[5'hD][7:6];	// src/main/scala/RayTrace.scala:131:7, :195:26, :197:25
        closestT_value = _RANDOM[5'hD][23:8];	// src/main/scala/RayTrace.scala:131:7, :195:26, :199:25
        closestObj = _RANDOM[5'hD][31:24];	// src/main/scala/RayTrace.scala:131:7, :195:26, :200:27
        allTested = _RANDOM[5'h10][0];	// src/main/scala/RayTrace.scala:131:7, :203:26
        hitPoint_x_value = _RANDOM[5'h10][17:2];	// src/main/scala/RayTrace.scala:131:7, :203:26, :206:25
        hitPoint_y_value = {_RANDOM[5'h10][31:18], _RANDOM[5'h11][1:0]};	// src/main/scala/RayTrace.scala:131:7, :203:26, :206:25
        hitPoint_z_value = _RANDOM[5'h11][17:2];	// src/main/scala/RayTrace.scala:131:7, :206:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/RayTrace.scala:131:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/RayTrace.scala:131:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_sphereAddr = state == 3'h5 ? shadowSphereIdx : sphereIdx;	// src/main/scala/RayTrace.scala:131:7, :178:22, :195:26, :196:32, :272:{23,30}
  assign io_lightAddr = lightIdx;	// src/main/scala/RayTrace.scala:131:7, :197:25
  assign io_busy = |state;	// src/main/scala/RayTrace.scala:131:7, :178:22, :269:21
  assign io_frameComplete = ~_GEN_8 & (&state) & _GEN_11;	// src/main/scala/RayTrace.scala:131:7, :178:22, :270:17, :271:20, :274:16, :278:17, :440:37
  assign io_asciiChar =
    _GEN_9
      ? 8'h20
      : {1'h0, _GEN[_charIndex_T_2[19:8] > 12'h9 ? 4'h9 : _charIndex_T_2[11:8]]};	// src/main/scala/RayTrace.scala:131:7, :227:50, :274:16, :278:17, :433:{37,57}, :434:{30,41}, :435:20
  assign io_asciiValid = ~_GEN_8 & (&state);	// src/main/scala/RayTrace.scala:131:7, :178:22, :270:17, :274:16, :278:17
  assign io_x = _GEN_9 ? 7'h0 : pixelX;	// src/main/scala/RayTrace.scala:131:7, :180:23, :274:16, :275:8, :278:17
  assign io_y = _GEN_9 ? 6'h0 : pixelY;	// src/main/scala/RayTrace.scala:131:7, :181:23, :274:16, :276:8, :278:17
endmodule

